Add/small cleanup
woocommerce/sift-for-woocommerce pull request #18
Opened 2024-11-22 14:54 UTC by millerf

#### Changes proposed in this Pull Request

* Added a README for the Sift webhooks
* Fix name of a key for the webhook endpoint
* Remove unecessary file (`abuse-decisions-action.php`)
* Change file hierarchy and harmonize file/class names

#### Testing instructions

* Make sure everything works.

2024-11-22 15:53 UTC, chrisfromthelc requested changes
Looks like some linter issues and a bad file requirement in the payment gateway test.

2024-11-22 15:53 UTC, chrisfromthelc commented on tests/PaymentGatewayTest.php
>  require_once __DIR__ . '/../src/inc/payment-gateway.php';
I think this line needs to be removed/changed.

2024-11-22 17:32 UTC, chrisfromthelc approved these changes, later dismissed

2024-11-25 08:49 UTC, millerf reviewed
LGTM. But I cannot approve.

2024-11-25 16:55 UTC, chrisfromthelc approved these changes
Approving for @millerf

2024-11-25 18:07 UTC, merged